# Use OpenJDK image to run your jar file
FROM openjdk:17-jdk-slim

# Copy the jar file from builder stage
COPY target/rs-0.0.1-SNAPSHOT.jar /usr/app/my-app.jar

# Set the working directory
WORKDIR /usr/app
EXPOSE 8081
# Command to run the application
ENTRYPOINT ["java","-jar","my-app.jar"]
